### ISSUE TITLE
Obsidian fails to load the plugin

### ISSUE THREAD

**Issue by RobberFox** [Opisek/obsidian-vim-langmap#1]
I would have wanted to post this in discussion, but I don't see one, since it's just me not knowing how to download this plugin properly. When I only putting the plugin folder into the Obsidian's plugin folder - I get and error: `Failed to load plugin obsidian-vim-langmap`
![image](https://github.com/Opisek/obsidian-vim-langmap/assets/142990781/afce7a60-6d9b-437d-949a-36b424fa3732)
What should I do with the other `autohotkey` and `switcher` folders?

**Comment by Opisek** [comment]
Hi, thanks for taking interest in my plugin. I should probably make a proper release soon, but let me preliminarily provide you with the necessary file layout.

You need to create ``obsidian-vim-langmap`` directory in Obsidian's plugins folder, but I believe you've already got that right. Inside that directory, you need:
- `main.js` (created by compiling the plugin using `npm install && npm run build` in the `plugin` directory of the source code)
- `manifest.json`
- `styles.css`
- `NextLayout.exe`
- `PreviousLayout.exe`
- `KeyboardSwitcher.exe`

All these files must go in the same plugin root directory.

I hope that helps you out. Otherwise, I could look into making a pre-compiled release in the near future, as well as putting it up in Obsidian's community plugins.

**Comment by RobberFox** [comment]
Thank you for a concise guide - the plugin works! I just want to ask about the Typing/Vim keyboard offset. Currently I have 0 offset on both - which turns the language to typing (Armenian in my case) **everytime** I enter typing (insert) mode. But for typing and editing equations I need English instead of Armenian. Can I tweak the offset to have this sequence: `certain language` -> `normal (aka. edit) mode and switching to US QWERTY` -> `back to that certain language`. Basically - preserve the language I was typing in.
P.S. I only have 2 keyboard input languages: US, Armenian

**Comment by Opisek** [comment]
Due to a bug in Windows API I was unfortunately not able to do it. However, I am currently developing a more true-to-vim langmap which should allow what you're looking for. In your case it would simple remap Armenian characters to QWERTY, but leave the actual system layout untouched - so it won't switch back and forth between different layouts. The development of that might take a longer while though.

**Comment by RobberFox** [comment]
Okay, in any case. I already know multiple guys that I will share this plugin to - they will benefit from it a lot. Thank you for your work!

**Comment by Opisek** [comment]
Good news, @RobberFox. I went up the dependency chain and added the missing feature on [CodeMirror's part](https://github.com/replit/codemirror-vim/pull/151). It will be blissfully simple to utilize proper langmap as soon as Obsidian update their CodeMirror Vim dependency.
